CJK_UNIT
#中文单位词库
##长度##
千米/q/qian mi/公里/length.km
米/q/mi/null/length.m
分米/q/fen mi/null/length.dm
厘米/q/li mi/null/length.cm
毫米/q/hao mi/null/length.mm
微米/q/wei mi/null/length.um
纳米/q/na mi/null/length.nm
英寸/q/ying cun/null/length.in
英尺/q/ying chi/null/length.ft
码/q/ma/null/length.yd
英寻/q/ying xun/null/length.fm
弗隆/q/fu long/null/length.fur
丈/q/zhang/null/length.tft
尺/q/chi/null/length.cft
寸/q/cun/null/length.cin
#分
#厘
#毫
##距离##
里/distance.li
英里/distance.mi
海里/distance.nmi
公里/distance.km
光年/distance.ly
##时间
年/time.y
月/time.m
周/time.w
天/time.d
日/time.d
时/time.h
时半/time.hi
时一刻/time.hi
点/time.h
点半/time.hi
点一刻/time.hi
分/time.i
秒/time.s
毫秒/time.ms
微秒/time.um
纳秒/time.ns
小时/time.h
分钟/time.m
##货币##
元/currency.cny
人民币/currency.cny
港元/currency.hkd
港币/currency.hkd
美元/currency.usd
美金/currency.usd
刀/currency.usd
澳门元/currency.mop
澳元/currency.mop
台币/currency.twd
新台币/currency.twd
朝鲜元/currency.kwp
欧元/currency.eur
韩元/currency.krw
越南盾/currency.vnd
日元/currency.jpy
新加坡元/currency.sgd
澳大利亚元/currency.aud
泰铢/currency.thb
泰国铢/currency.thb
缅元/currency.buk
卢比/currency.inr
英镑/currency.gbp
法郎/currency.frf
加元/currency.cad
加拿大元/currency.cad
马克/currency.dem
里拉/currency.itl
埃及镑/currency.egp
新西兰元/currency.nzd
林吉特/currency.myr
卢布/currency.sur
兰特/currency.zar
南非兰特/currency.zar
比索/currency.php
菲律宾比索/currency.php
墨西哥比索/currency.mxp
古巴比索/currency.cup
克朗/currency.skk
冰岛克朗/currency.isk
瑞典克朗/currency.sek
丹麦克朗/currency.dkk
挪威克朗/currency.nok
捷克克朗/currency.csk
##体积##
立方米/volume.m3
立方分米/volume.dm3
立方厘米/volume.cm3
立方毫米/volume.mm3
升/volume.l
分升/volume.dl
厘升/volume.cl
毫升/volume.ml
微升/volume.ul
纳升/volume.nl
公石/volume.hl
立方英尺/volume.ft3
立方英寸/volume.in3
立方码/volume.yd3
亩英尺/volume.mft
英制加仑/volume.gal.uk
美制加仑/volume.gal.us
#斗
##重量##
#公制
千克/quality.kg
克/quality.g
毫克/quality.mg
吨/quality.t
公担/quality.q
#英制
磅/quality.lb
盎司/quality.oz
克拉/quality.ct
格令/quality.gr
长吨/quality.lt
短吨/quality.st
英担/quality.dan.uk
美担/quality.dan.us
英石/quality.bp
打兰/quality.dr
#市制
担/quality.dan
斤/quality.jin
两/quality.liang
钱/quality.qian
##面积##
#公制
平方千米/area.km2
平方米/area.m2
平方分米/area.dm2
平方厘米/area.cm2
平方毫米/area.mm2
平方微米/area.um2
平方纳米/area.nm2
公顷/area.ha
公亩/area.are
#英制
英亩/area.acre
平方英里/area.sq.mi
平方码/area.sq.yd
平方英尺/area.sq.ft
平方英寸/area.sq.in
平方竿/area.sq.rd
#市制
顷/area.qing
亩/area.mu
平方尺/area.ft2
平方寸/area.in2
##温度##
摄氏度/temperature.c
华氏度/temperature.f
开氏度/temperature.k
兰氏度/temperature.r
列氏度/temperature.re
##力##
牛/force.n
千牛/force.kn
千克力/force.kgf
克力/force.gf
公吨力/force.tf
磅力/force.lbf
千磅力/force.kip
##压力##
帕斯卡/pressure.pa
千帕/pressure.kpa
千帕斯卡/pressure.kpa
百帕/pressure.hpa
标准大气压/pressure.atm
毫米汞柱/pressure.hg.mm
英寸汞柱/pressure.hg.in
巴/pressure.bar
毫巴/pressure.mbar
毫米水柱/pressure.wg.mm
##角度##
#角度制
圆周/angle.360
直角/angle.90
百分度/angle.gon
#度(°)
#分( ′)
#秒(")
#弧度制
弧度/angle.rad
毫弧度/angle.mrad
#数据存储
比特/storage.bit
字节/storage.b
千字节/storage.kb
兆字节/storage.mb
千兆字节/storage.gb
太字节/storage.tb
拍字节/storage.pb
艾字节/storage.eb
#其他
担/dan
瓶/bottle
袋/bag
盒/box
折/discount
件/item
℃/temperature.c
℉/temperature.f
°R/temperature.r
°Re/temperature.re
°RE/temperature.re
°/angle.du
′/angle.fen
